name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build with ESLint disabled
        run: DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Configure Git
        run: |
          cd build
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Deploy to gh-pages
        run: |
          cd build
          git add .
          git commit -m "Deploy: ${{ github.sha }}"
          git branch -M gh-pages
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
